services:
  clickhouse:
    image: altinity/clickhouse-server:22.8
    container_name: clickhouse
    ports:
      - "8123:8123"   
      - "9000:9000"  
    volumes:
      - ./clickhouse/init:/docker-entrypoint-initdb.d 
      - clickhouse_data:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: ["CMD", "curl", "-s", "http://localhost:8123/ping"]
      interval: 5s
      timeout: 2s
      retries: 24

  clickhouse-client:
    image: clickhouse/clickhouse-client:latest
    container_name: clickhouse-client
    depends_on:
      - clickhouse
    entrypoint:
      - /bin/sh
      - -c
      - |
        exec clickhouse-client --host clickhouse


volumes:
  clickhouse_data:
